//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servisler
    {
        public System.Guid ID { get; set; }
        public string ServisAdi { get; set; }
        public string EskiServisAdi { get; set; }
        public string EskiServisURL { get; set; }
        public string YeniServisURL { get; set; }
        public string ServerIP { get; set; }
        public Nullable<int> ServisTipId { get; set; }
    
        public virtual ServisTip ServisTip { get; set; }
    }
}
